services:
  postgres:
    image: docker.io/postgis/postgis:18-3.6
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - 127.0.0.1:${PGPORT}:5432
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "--host=127.0.0.1", "--quiet" ]
      start_period: 30s
      start_interval: 2s
    restart: always
  llama-cpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda13
    command: [ --port, "8000", --models-preset, /config/models.ini, --models-max, "1" ]
    devices:
      - nvidia.com/gpu=all
    volumes:
      - ./config/models.ini:/config/models.ini:ro,Z
      - ~/.cache/huggingface/:/root/.cache/huggingface/:Z
    ports:
      - 127.0.0.1:8000:8000
    healthcheck:
      test: [ "CMD", "curl", "--request", "GET", "--fail", "--silent", "--show-error", "--output", "/dev/null", "http://localhost:8000/health" ]
      start_period: 15m
      start_interval: 5s
    restart: always

volumes:
  postgres:
