[tools]
"aqua:Kampfkarren/selene" = "latest"
"conda:docker-compose" = "latest"
"github:microsoft/apm" = "latest"
pixi = "latest"
rumdl = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
tombi = "latest"
typst = "latest"
typstyle = "latest"
